name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: test

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: ip r
